### ISSUE TITLE
Mod 0 Assessment Results

### ISSUE THREAD

**Issue by katiescruggs** [David5280/mod_0_skills#1]
# Checklist/Rubric

#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub
* [ ]  Directories are named correctly.
> classes directory is missing
* [x]  Files are named correctly.
* [ ]  Files and directories are structured correctly.
> classes directory is missing
* [x]  Initial commit was made.
* [x]  Initial commit was pushed to GitHub.

#### Part II: Top Down Design
* [x]  Larger processes were broken into smaller layers.
* [ ]  Changes were added and committed with a properly formatted commit message starting with a verb and a capital letter.
> Missing the capital letter, but the message is nice and descriptive.
* [x]  Changes were pushed to Github.

#### Part III: Classes in a System
* [ ]  Directories and files were named and structured correctly.
> Missing classes directory
* [x]  The attributes chosen for **Class #1** represent states or characteristics.
* [x]  The attributes chosen for **Class #2** represent states or characteristics.
* [x]  The attributes chosen for **Class #3** represent states or characteristics.
* [x]  The methods chosen for **Class #1** represent behaviors or actions.
* [x]  The methods chosen for **Class #2** represent behaviors or actions.
* [x]  The methods chosen for **Class #3** represent behaviors or actions.
* [x]  Data type (string, integer, boolean, array, hash/object, datetime) were identified for each attribute in all three classes.
* [x]  Individual changes were added and committed separately with a properly formatted commit message.
> Commit messages should begin with a capital letter. Also, it looks like you duplicated "Initial commit" as a message, but the other messages look good!
* [x]  Changes were pushed to Github.

**Mod 0 Technical Assessment Results**

* [ ]   Technical Ready
* [x]   Pending
* [ ]   Not Ready

**Comment by katiescruggs** [comment]
Good job on your assessment, David! I just want you to make one change and then you will be deemed `Technical Ready`. Please create a directory called `classes`, and put your three class files into that directory. Then add a commit message starting with a verb and a capital letter to describe this change and push it up to GitHub. Please DM me, Rachel, and Tim when that task is completed. Thanks!

**Comment by katiescruggs** [comment]
Changes were made -- status is now `Technical Ready`. Thank you!
